

markdown: kramdown

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Candyman's site”
title: Candyman's site
description: Everything about Candyman.
url: localhost:4000
feed: /atom.xml
author_info: <a href="http://a774032767.github.io/">Candyman</a>
